orders = [
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "NIFTYBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 494,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "NIFTYBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 494,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "JUNIORBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 111,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "JUNIORBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 111,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "BANKBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 143,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "BANKBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 143,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "PSUBNKBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 248,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "PSUBNKBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 248,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "AUTOBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 72,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "AUTOBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 72,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "ITBEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 1034,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "ITBEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 1034,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "PHARMABEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 305,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "PHARMABEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 305,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "MID150BEES",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 113,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "MID150BEES",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 113,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "HDFCSML250",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 108,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "HDFCSML250",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 108,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "CPSEETF",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 687,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "CPSEETF",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 687,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "ICICIB22",
        "transaction_type": "BUY",
        "order_type": "LIMIT",
        "quantity": 100,
        "price": abc,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    },
    {
        "variety": "regular",
        "exchange": "NSE",
        "tradingsymbol": "ICICIB22",
        "transaction_type": "SELL",
        "order_type": "LIMIT",
        "quantity": 100,
        "price": xyz,
        "product": "MIS",
        "validity": "TTL",
        "validity_ttl": "1"
    }
]